//CLK
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN E3} [get_ports CLK]
//按键
set_property PACKAGE_PIN N17 [get_ports reset]
set_property PACKAGE_PIN P18 [get_ports NEXT_CP_ini]
//数字输入
set_property PACKAGE_PIN V5 [get_ports {IN[7]}]
set_property PACKAGE_PIN T4 [get_ports {IN[6]}]
set_property PACKAGE_PIN V6 [get_ports {IN[5]}]
set_property PACKAGE_PIN T5 [get_ports {IN[4]}]
set_property PACKAGE_PIN T6 [get_ports {IN[3]}]
set_property PACKAGE_PIN V7 [get_ports {IN[2]}]
set_property PACKAGE_PIN R8 [get_ports {IN[1]}]
set_property PACKAGE_PIN U9 [get_ports {IN[0]}]
//开关
set_property PACKAGE_PIN V15 [get_ports SET]
set_property PACKAGE_PIN R15 [get_ports TYPE]
set_property PACKAGE_PIN U16 [get_ports EN]
//数码管 
set_property IOSTANDARD LVCMOS18 [get_ports {AN[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AN[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AN[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AN[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AN[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AN[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AN[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AN[0]}]
set_property PACKAGE_PIN C9 [get_ports {AN[7]}]
set_property PACKAGE_PIN C10 [get_ports {AN[6]}]
set_property PACKAGE_PIN D10 [get_ports {AN[5]}]
set_property PACKAGE_PIN C11 [get_ports {AN[4]}]
set_property PACKAGE_PIN M17 [get_ports {AN[3]}]
set_property PACKAGE_PIN J14 [get_ports {AN[2]}]
set_property PACKAGE_PIN K13 [get_ports {AN[1]}]
set_property PACKAGE_PIN P14 [get_ports {AN[0]}]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN F14} [get_ports {SEG[7]}]
set_property -dict {IOSTANDARD LVCMOS19 PACKAGE_PIN N14 } [get_ports {SEG[6]}]
set_property -dict {IOSTANDARD LVCMOS20 PACKAGE_PIN J13 } [get_ports {SEG[5]}]
set_property -dict {IOSTANDARD LVCMOS21 PACKAGE_PIN G13 } [get_ports {SEG[4]}]
set_property -dict {IOSTANDARD LVCMOS22 PACKAGE_PIN F13 } [get_ports {SEG[3]}]
set_property -dict {IOSTANDARD LVCMOS23 PACKAGE_PIN G14 } [get_ports {SEG[2]}]
set_property -dict {IOSTANDARD LVCMOS24 PACKAGE_PIN M13 } [get_ports {SEG[1]}]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN H14} [get_ports {SEG[0]}]
//

set_property IOSTANDARD LVCMOS18 [get_ports {IN[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {IN[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {IN[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {IN[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {IN[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {IN[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {IN[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {IN[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {alert[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {alert[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {alert[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {alert[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {alert[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {alert[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {alert[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {alert[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SEG[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SEG[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SEG[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SEG[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SEG[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SEG[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports EN]
set_property IOSTANDARD LVCMOS18 [get_ports NEXT_CP_ini]
set_property IOSTANDARD LVCMOS18 [get_ports reset]
set_property IOSTANDARD LVCMOS18 [get_ports SET]
set_property IOSTANDARD LVCMOS18 [get_ports TYPE]
set_property PACKAGE_PIN U6 [get_ports {alert[7]}]
set_property PACKAGE_PIN R5 [get_ports {alert[6]}]
set_property PACKAGE_PIN U7 [get_ports {alert[5]}]
set_property PACKAGE_PIN R6 [get_ports {alert[4]}]
set_property PACKAGE_PIN R7 [get_ports {alert[3]}]
set_property PACKAGE_PIN U8 [get_ports {alert[2]}]
set_property PACKAGE_PIN T8 [get_ports {alert[1]}]
set_property PACKAGE_PIN V9 [get_ports {alert[0]}]
