set_property IOSTANDARD LVCMOS18 [get_ports {AN[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AN[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AN[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AN[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MainLight[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MainLight[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MainLight[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports {SubLight[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SubLight[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SubLight[0]}]


set_property PACKAGE_PIN P14 [get_ports {AN[0]}]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN F14} [get_ports {SEG[7]}]
set_property -dict {IOSTANDARD LVCMOS19 PACKAGE_PIN N14 } [get_ports {SEG[6]}]
set_property -dict {IOSTANDARD LVCMOS20 PACKAGE_PIN J13 } [get_ports {SEG[5]}]
set_property -dict {IOSTANDARD LVCMOS21 PACKAGE_PIN G13 } [get_ports {SEG[4]}]
set_property -dict {IOSTANDARD LVCMOS22 PACKAGE_PIN F13 } [get_ports {SEG[3]}]
set_property -dict {IOSTANDARD LVCMOS23 PACKAGE_PIN G14 } [get_ports {SEG[2]}]
set_property -dict {IOSTANDARD LVCMOS24 PACKAGE_PIN M13 } [get_ports {SEG[1]}]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN H14} [get_ports {SEG[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports {Seg[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Seg[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Seg[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Seg[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Seg[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Seg[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Seg[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Seg[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports CLK]
set_property IOSTANDARD LVCMOS18 [get_ports CLR]
set_property IOSTANDARD LVCMOS18 [get_ports pause]
set_property IOSTANDARD LVCMOS18 [get_ports start]
set_property IOSTANDARD LVCMOS18 [get_ports stopa]
set_property IOSTANDARD LVCMOS18 [get_ports stopb]

set_property SLEW SLOW [get_ports {AN[3]}]
set_property SLEW SLOW [get_ports {AN[2]}]
set_property SLEW SLOW [get_ports {AN[1]}]
set_property SLEW SLOW [get_ports {AN[0]}]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets stopa_IBUF]



set_property PACKAGE_PIN J14 [get_ports {AN[2]}]
set_property PACKAGE_PIN K13 [get_ports {AN[1]}]
set_property PACKAGE_PIN R7 [get_ports {SubLight[2]}]
set_property PACKAGE_PIN U8 [get_ports {SubLight[1]}]
set_property PACKAGE_PIN T8 [get_ports {SubLight[0]}]
set_property PACKAGE_PIN R5 [get_ports {MainLight[1]}]
set_property PACKAGE_PIN U6 [get_ports {MainLight[2]}]
set_property PACKAGE_PIN U7 [get_ports {MainLight[0]}]
set_property PACKAGE_PIN F14 [get_ports {Seg[7]}]
set_property PACKAGE_PIN M17 [get_ports {AN[3]}]
set_property PACKAGE_PIN N14 [get_ports {Seg[6]}]
set_property PACKAGE_PIN J13 [get_ports {Seg[5]}]
set_property PACKAGE_PIN F13 [get_ports {Seg[3]}]
set_property PACKAGE_PIN G13 [get_ports {Seg[4]}]
set_property PACKAGE_PIN G14 [get_ports {Seg[2]}]
set_property PACKAGE_PIN M13 [get_ports {Seg[1]}]
set_property PACKAGE_PIN H14 [get_ports {Seg[0]}]
set_property PACKAGE_PIN V6 [get_ports stopa]
set_property PACKAGE_PIN E3 [get_ports CLK]
set_property PACKAGE_PIN N17 [get_ports CLR]
set_property PACKAGE_PIN V5 [get_ports pause]
set_property PACKAGE_PIN T4 [get_ports start]
set_property PACKAGE_PIN T5 [get_ports stopb]

set_property PACKAGE_PIN C9 [get_ports {AN[7]}]
set_property PACKAGE_PIN C10 [get_ports {AN[6]}]
set_property PACKAGE_PIN D10 [get_ports {AN[5]}]
set_property PACKAGE_PIN C11 [get_ports {AN[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AN[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AN[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AN[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AN[4]}]
